# Port standar untuk mikrokontroler (Tim C) dan script Python kita
listener 1883 0.0.0.0
allow_anonymous true

# Port WebSockets untuk aplikasi Web/React (Tim A)
listener 9001 0.0.0.0
protocol websockets